@extends('layoults.arequipacosas')
@section('arequipacosas')

	<div class="politica">
		<h1> Términos y Condiciones </h1>
<p>Los términos y condiciones de la empresa  <label>Arequipacosas.com</label> son aplicables a todos los negocios-clientes disponibles online, a través de cualquier dispositivo móvil, por correo electrónico o por teléfono. Al acceder, navegar y utilizar nuestro sitio web a través de la plataforma (en adelante, mencionados de forma conjunta como "el sitio web"), aceptas haber leído, entendido y estar de acuerdo con los términos y condiciones que se muestran a continuación.</p>
<p>Estas páginas, su contenido, estructura, infraestructura y el servicio de publicidad online que proporcionan a través de este sitio web pertenecen y son gestionadas y suministradas por NL Coorporation Web y se ponen a tu disposición solo para un uso personal, no comercial, conforme a los términos y condiciones especificado a continuación.</p>
 
<h3>1. ÁMBITO DE NUESTRO SERVICIO</h3>
<p>A través de la Plataforma, <label>Arequipacosas.com</label> (en distribución) proporcionamos una plataforma online a través de la cual los Negocios pueden anunciar sus productos y/o Servicios, a través del cual, los que visitan la plataforma pueden visualizar la  información publicitaria de cada anunciante. Al visitar la plataforma  <label>Arequipacosas.com</label>, establece una relación contractual directa (legalmente vinculante) con el Proveedor con el que has reservado o al que le has comprado un producto o servicio (según corresponda). Desde el momento en que visitas y  la información  de  los proveedores, nosotros actuamos únicamente como intermediarios entre Tú y el Negocio.</p>
<p>Al prestar nuestro Servicio, la información que mostramos está basada en la información que nos proporcionan los Negocios anunciantes. Como tales, los Negocios tienen acceso a un registro mediante la cual se hacen totalmente responsables de actualizar las tarifas, la disponibilidad y los otros datos que aparecen en nuestra Plataforma. Aunque intentamos que nuestro Servicio sea lo más preciso posible, no podemos verificar ni garantizar que toda la información sea exacta, completa o correcta. Tampoco nos hacemos responsables de errores (como errores manifiestos y tipográficos), interrupciones (debido a caídas (temporales y/o parciales) del servidor o a reparaciones, actualizaciones y mantenimiento de nuestra Plataforma u otros motivos), información imprecisa, engañosa o falsa, o falta de información. Cada Proveedor es responsable en todo momento de la precisión, la exactitud y la corrección de la información (tanto descriptiva como referente a tarifas y disponibilidad) que aparece en nuestra Plataforma. Nuestra Plataforma no constituye ni debe ser vista como una recomendación o promoción de la calidad, el nivel de servicio, la calificación o clasificación (por estrellas) de ningún Negocios (o sus instalaciones, recinto, productos o servicios) disponible.</p>
<p>Nuestro Servicio está disponible únicamente para uso personal y no comercial. Por lo tanto, no está permitido revender, realizar deep-links, utilizar, copiar, monitorizar (por ejemplo, spider, scrape), mostrar, descargar o reproducir el contenido, la información, el software, las reservas, las entradas, los productos o los servicios disponibles en nuestra Plataforma para cualquier actividad o fin comercial o competitivo.</p>
<h3>2. PRECIOS, TARIFAS TACHADAS Y PRECIO MÍNIMO GARANTIZADO</h3>
<p>Los precios son de manejo  interno con  el  Negocio anunciante. Todos los precios por  establecimientos  impuestos sobre ventas incluidos y cualquier otro impuesto (sujeto a cambios de dichos impuestos), a no ser que se indique de otra forma en nuestra Plataforma.</p>
<p>En ocasiones, en nuestra Plataforma hay una tarifa más barata para un servicio, producto o estancia específica. (Por promoción) Sin embargo, estas tarifas puestas a disposición por los Negocios pueden comportar restricciones y condiciones especiales. Queremos que pagues el precio más bajo posible por tu publicidad  online.</p> 
<p>Los errores evidentes (erratas incluidas) no son vinculantes.</p>
<p>Todas las ofertas especiales y promociones están marcadas como tal.</p>
<h3>3. UN ÚNICO PAGO ANUAL</h3> 
<p>La plataforma  <label>Arequipacosas.com</label>, sólo advierte un único pago (para ingreso y publicidad anual). Se garantiza la estadia permanente por un año y nuestro servicio de estadía y de actualización de su plantilla web, es gratuito porque, a diferencia de otros, no te cobramos por nuestro Servicio ni añadimos suplementos.</p>
<p>Los negocios anunciantes pagan una comisión (un porcentaje pequeño por dia para su  publicación online),  <label>Arequipacosas.com</label> recibe ese pago de manera anticipada y anual y lo cobra al iniciar el contrato, y lo vuelve a requerir después de 365 días.</p>
<h3>4. PAGO POR ADELANTADO, CANCELACIÓN</h3>
<p>Al realizar la  publicación online con en  la  plataforma de  <label>Arequipacosas.com</label> aceptas sus condiciones de cancelación. Aquí se incluyen los servicios y/o productos ofertados por el negocio anunciante. Las condiciones generales de cancelación de cada Negocio están determinadas y dispuestas por nuestros únicos ejecutivos y responsables de la plataforma (Nestor Coa y Lucero Huayta). Quienes al término de estas líneas, detallarán mayor información de la Garantía de publicación del negocio en la Plataforma.</p>
<h3>7. CORRESPONDENCIA Y COMUNICACIÓN (ADICIONAL)</h3>
<p><label>Arequipacosas.com</label> se exime de cualquier responsabilidad en relación con cualquier comunicación con el negocio anunciante en o a través de su plataforma. No obtendrás ningún derecho de ninguna petición a, o comunicación con el negocio o (cualquier forma de) acuse de recibo de cualquier comunicación o petición.  <label>Arequipacosas.com</label> no puede garantizar que el negocio anunciante (debida y oportunamente) reciba/lea, cumpla con, ejecute o acepte cualquier petición o comunicación.</p>
<p>Con el objetivo de completar y asegurar tu anuncio adecuadamente, necesitas usar una dirección y ubicación sectorizada correcta. No nos hacemos responsables de (ni tenemos ninguna obligación de verificar) ningún error o fallo ortográfico en la dirección o ubicación del negocio ni de ningún número de teléfono (móvil) que sea impreciso o erróneo.</p>
<p>Cualquier queja o reclamación contra  <label>Arequipacosas.com</label> o respecto al Servicio que presta debe hacerse de forma inmediata, antes de la cancelación de la única cuota anual y de acceso al espacio gratuito que se brinda. Cualquier queja o reclamación enviada fuera de esta disposición queda rechazada y el demandante perderá todo derecho a cualquier tipo de reclamo.</p>
<h3>8. RANKING DE NEGOCIOS</h3>
<p>La clasificación de los Negocios anunciantes que aparece por defecto en nuestra Plataforma es por Recomendados (o similares) (y lo llamamos "Ranking por defecto"). También ofrecemos otras formas de clasificar los Negocios. El Ranking por defecto se crea a través de un sistema automático de clasificación (algoritmo) y se basa en diversos criterios, en los que se incluyen no solo la popularidad de un Negocio entre nuestros visitantes sino también por la ubicación, rubro, historial de búsqueda y por publicación de su anuncio (El último anunciante es el primero que se visualiza).</p>
<h3>9. EXENCIÓN DE RESPONSABILIDAD</h3>
<p>En la medida en que esté permitido por la ley, ni nosotros ni ninguno de nuestros directores, empleados, representantes, subsidiarios, apoderados u otras personas involucradas en el proceso de creación, patrocinio y promoción del sitio web y sus contenidos será responsable de: (i) pérdidas o daños punitivos, especiales, indirectos o consecuentes, pérdidas de producción, de beneficios, ingresos, contratos, así como de pérdidas o daños de clientes o de reputación y pérdidas de demandas; (ii) errores relacionados con la descripción de la información (incluida la información sobre precios, disponibilidad y clasificaciones) del Negocio anunciante en nuestra Plataforma; (iii) servicios prestados o productos ofertados por el Negocio anunciante u otros socios de negocio; (iv) pérdidas, daños o costes (directos, indirectos, consecuentes o punitivos) que sufras, contraigas o pagues, surgidos o relativos al uso, indisponibilidad o retraso de nuestra Plataforma; o (v) cualquier tipo de perjuicio (personal), muerte, daño de la propiedad u otros daños, pérdidas y gastos (directos o indirectos, consecuentes o punitivos) que sufras, contraigas o pagues, ya sea a causa de actos (legales), errores, infracciones, negligencias (evidentes), mala conducta profesional deliberada, omisiones, incumplimientos, representación errónea, responsabilidad extracontractual objetiva o (completa o parcialmente) atribuible al Negocio o a otros socios de negocio (incluyendo cualquiera de sus empleados, directores, personal, apoderados, representantes o empresas afiliadas) cuyos productos o servicios (directa o indirectamente) estén disponibles, se oferten o promocionen en o a través de nuestra Plataforma, incluyendo cualquier cancelación (parcial), huelga, fuerza mayor u otro acto que escape a nuestro control.</p>
<p>Arequipacosas.com no es responsable del envío, recogida, retención o pago de los impuestos sobre el precio (de sus productos) a las autoridades fiscales pertinentes. Arequipacosas.com no actúa como vendedor oficial de ningún producto o servicio disponible en la Plataforma.</p>
<p>Al subir fotos u otras imágenes a nuestro sistema certificas, garantizas y confirmas que estás en posesión del copyright de la foto/imagen y que estás de acuerdo con que  <label>Arequipacosas.com</label> utilice dicha foto o imagen en sus webs (móviles), apps y materiales promocionales (online y offline), así como en cualquier publicación que Arequipacosas.com considere apropiada. Estás garantizando a Arequipacosas.com un derecho no-exclusivo, universal, irrevocable, incondicional y permanente, así como la licencia para utilizar, reproducir, mostrar, hacer reproducir, distribuir, sublicenciar, comunicar y facilitar las fotos/imágenes en la forma que Arequipacosas.com considere apropiada. Al subir estas fotos/imágenes, la persona que las sube acepta la responsabilidad legal y moral sobre todas y cada una de las reclamaciones legales realizadas por un tercero (incluyendo, pero no limitándose a, los propietarios de los negocios anunciantes) a raíz del uso y publicación de las fotos/imágenes por parte de Arequipacosas.com. Arequipacosas.com no posee ni avala de forma alguna las fotos/imágenes que se suben. La veracidad, validez y derecho de uso de todas las fotos/imágenes la asumirá la persona que ha subido la foto, y nunca será responsabilidad de Arequipacosas.com. Arequipacosas.com niega cualquier responsabilidad u obligación sobre las fotografías publicadas. La persona que ha subido las fotos garantiza que las fotos/imágenes no contienen ningún virus, troyano o archivos infectados, así como ningún material pornográfico, ilegal, obsceno, ofensivo, censurable o inapropiado, y que no infringe los derechos (de propiedad intelectual, de copyright o de privacidad) de terceros. Cualquier foto/imagen que no cumpla con los requisitos mencionados no será publicada y/o puede ser eliminada por Arequipacosas.com en cualquier momento y sin previo aviso.</p>
<h3>10. DERECHOS DE PROPIEDAD INTELECTUAL</h3>
<p>Si no se indica lo contrario, el software necesario para nuestros servicios o disponible o utilizado por nuestra Plataforma y los derechos de propiedad intelectual  de los contenidos y la información, así como el material de nuestra Plataforma pertenecen a  <label>Arequipacosas.com</label>.</p>
<p>Arequipacosas.com se reserva exclusivamente la propiedad de todos los derechos, título e interés en (todos los derechos de propiedad intelectual de) (la apariencia (incluyendo la infraestructura) de) la Plataforma donde el servicio tiene disponibilidad, y no tienes derecho a copiar, recopilar, enlazar a, publicar, promocionar, vender, integrar, utilizar, combinar o utilizar el contenido  o nuestra marca sin un permiso por escrito nuestro. En la medida que quieras usar (completamente o parcialmente) nuestro contenido (traducido) o seas propietario de cualquier derecho de propiedad intelectual de la Plataforma o cualquier, por la presente, transfieres y cedes todos los derechos de propiedad intelectual a Arequipacosas.com. Cualquier tipo de uso indebido o cualquier tipo de acción o comportamiento anteriormente mencionado constituirá una infracción de nuestros derechos de propiedad intelectual (incluyendo el copyright y el derecho de base de datos).</p>
<h3>11. Miscelánea</h3>
<p>En la medida en que lo permita la ley, estos términos y condiciones y la prestación de nuestros servicios se regirán e interpretarán de acuerdo a la legislación de la Región Arequipa, y cualquier controversia que surja por estos términos y condiciones generales o por nuestros servicios se presentará únicamente ante los tribunales competentes.</p>
<p>Si alguna disposición de estos términos y condiciones es o se convierte en inválida o no vinculante, seguirás estando vinculado al resto de disposiciones mencionadas. Si esto ocurriese, la disposición no válida deberá cumplirse hasta el máximo permitido por la ley aplicable y, en la medida de lo posible, se aceptará un efecto similar al de las disposiciones inválidas o no vinculantes, conforme al contenido y objeto de estos términos y condiciones.</p>
<h3>12. SOBRE AREQUIPACOSAS.COM Y LAS EMPRESAS FILIALES</h3>
<p><label>Arequipacosas.com</label> presta el servicio de publicidad online. Se trata de una sociedad privada de responsabilidad limitada constituida según la legislación peruana y la sede de Arequipacosas.com se encuentra en la provincia de Arequipa –región  Arequipa. Estas empresas filiales proporcionan únicamente un apoyo interno a y en beneficio de Arequipacosas.com. Algunas empresas filiales específicas prestan servicios limitados de apoyo de atención al cliente (solo por teléfono). Las empresas filiales no cuentan con ninguna Plataforma (y de ninguna manera controlan, gestionan, mantienen ni son propietarias de la Plataforma). Las empresas filiales no tienen poder ni autoridad para prestar el servicio, representar a Arequipacosas.com o firmar un contrato en su nombre. No tienes ninguna relación (legal o contractual) con las empresas filiales. Las empresas filiales no operan y no están autorizadas para actuar como ningún tipo de agente de proceso o servicio de Arequipacosas.com.  <label>Arequipacosas.com</label> no acepta ni asume ningún otro domicilio en ningún lugar, ubicación u oficina del mundo (tampoco en la oficina de sus empresas filiales), que no sea su domicilio social de Arequipa.</p>
	</div>

@endsection